if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT)
    message(FATAL_ERROR "INPUT and OUTPUT are required")
endif()
file(READ "${INPUT}" PROFILE_TEXT)

function(require_value OUT REGEX LABEL)
    string(REGEX MATCH "${REGEX}" MATCHED "${PROFILE_TEXT}")
    if(NOT MATCHED)
        message(FATAL_ERROR "Missing ${LABEL} in ${INPUT}")
    endif()
    set(${OUT} "${CMAKE_MATCH_1}" PARENT_SCOPE)
endfunction()

require_value(BUILD "build[ \t]*=[ \t]*\"([^\"]+)\"" "build")
require_value(PE_TIMESTAMP "pe_timestamp[ \t]*=[ \t]*([0-9]+)" "pe_timestamp")
require_value(SIZE_OF_IMAGE "size_of_image[ \t]*=[ \t]*([0-9]+)" "size_of_image")
require_value(WINDOW_RVA "window_rva[ \t]*=[ \t]*([0-9]+)" "window_rva")
require_value(REGISTRY_RVA "registry_vector_rva[ \t]*=[ \t]*([0-9]+)" "registry_vector_rva")
require_value(FROZEN_RVA "registry_frozen_rva[ \t]*=[ \t]*([0-9]+)" "registry_frozen_rva")
require_value(CLASS_COUNT_RVA "class_count_rva[ \t]*=[ \t]*([0-9]+)" "class_count_rva")
require_value(ALLOCATE_RVA "engine_allocate_rva[ \t]*=[ \t]*([0-9]+)" "engine_allocate_rva")
require_value(FREE_RVA "engine_free_rva[ \t]*=[ \t]*([0-9]+)" "engine_free_rva")
require_value(OVERWRITE_SIZE "overwrite_size[ \t]*=[ \t]*([0-9]+)" "overwrite_size")
require_value(SIGNATURE "signature[ \t]*=[ \t]*\"([0-9A-Fa-f ]+)\"" "signature")

string(REGEX REPLACE " +" ";" SIGNATURE_BYTES "${SIGNATURE}")
set(SIGNATURE_LIST "")
set(SIGNATURE_SIZE 0)
foreach(BYTE IN LISTS SIGNATURE_BYTES)
    if(NOT BYTE MATCHES "^[0-9A-Fa-f][0-9A-Fa-f]$")
        message(FATAL_ERROR "Invalid signature byte '${BYTE}' in ${INPUT}")
    endif()
    string(APPEND SIGNATURE_LIST "0x${BYTE}, ")
    math(EXPR SIGNATURE_SIZE "${SIGNATURE_SIZE} + 1")
endforeach()
if(SIGNATURE_SIZE LESS OVERWRITE_SIZE)
    message(FATAL_ERROR "Signature is shorter than overwrite_size in ${INPUT}")
endif()

get_filename_component(OUTPUT_DIR "${OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
file(WRITE "${OUTPUT}" "#pragma once\n\nnamespace rml::platform::windows::generated\n{\n")
file(APPEND "${OUTPUT}" "inline constexpr std::array<std::uint8_t, ${SIGNATURE_SIZE}> kGlobalInitSignature{${SIGNATURE_LIST}};\n")
file(APPEND "${OUTPUT}" "inline constexpr EmbeddedBootstrapProfile kBootstrapProfile{\n")
file(APPEND "${OUTPUT}" "    ${PE_TIMESTAMP}u, ${SIZE_OF_IMAGE}u, \"${BUILD}\",\n")
file(APPEND "${OUTPUT}" "    ${WINDOW_RVA}u, ${REGISTRY_RVA}u, ${FROZEN_RVA}u, ${CLASS_COUNT_RVA}u, ${ALLOCATE_RVA}u, ${FREE_RVA}u,\n")
file(APPEND "${OUTPUT}" "    ${OVERWRITE_SIZE}u, kGlobalInitSignature.data(), kGlobalInitSignature.size()};\n")
file(APPEND "${OUTPUT}" "inline constexpr std::array kBootstrapProfiles{kBootstrapProfile};\n")
file(APPEND "${OUTPUT}" "}\n")
