if(NOT DEFINED INPUTS OR NOT DEFINED OUTPUT)
    message(FATAL_ERROR "INPUTS and OUTPUT are required")
endif()

function(require_value OUT REGEX LABEL TEXT SOURCE)
    string(REGEX MATCH "${REGEX}" MATCHED "${TEXT}")
    if(NOT MATCHED)
        message(FATAL_ERROR "Missing ${LABEL} in ${SOURCE}")
    endif()
    set(${OUT} "${CMAKE_MATCH_1}" PARENT_SCOPE)
endfunction()

set(PROFILE_DECLS "")
set(PROFILE_NAMES "")
set(PROFILE_INDEX 0)

foreach(INPUT IN LISTS INPUTS)
    file(READ "${INPUT}" PROFILE_TEXT)

    require_value(BUILD "build[ \t]*=[ \t]*\"([^\"]+)\"" "build" "${PROFILE_TEXT}" "${INPUT}")
    require_value(PE_TIMESTAMP "pe_timestamp[ \t]*=[ \t]*([0-9]+)" "pe_timestamp" "${PROFILE_TEXT}" "${INPUT}")
    require_value(SIZE_OF_IMAGE "size_of_image[ \t]*=[ \t]*([0-9]+)" "size_of_image" "${PROFILE_TEXT}" "${INPUT}")
    require_value(WINDOW_RVA "window_rva[ \t]*=[ \t]*([0-9]+)" "window_rva" "${PROFILE_TEXT}" "${INPUT}")
    require_value(REGISTRY_RVA "registry_vector_rva[ \t]*=[ \t]*([0-9]+)" "registry_vector_rva" "${PROFILE_TEXT}" "${INPUT}")
    require_value(FROZEN_RVA "registry_frozen_rva[ \t]*=[ \t]*([0-9]+)" "registry_frozen_rva" "${PROFILE_TEXT}" "${INPUT}")
    require_value(CLASS_COUNT_RVA "class_count_rva[ \t]*=[ \t]*([0-9]+)" "class_count_rva" "${PROFILE_TEXT}" "${INPUT}")
    require_value(ALLOCATE_RVA "engine_allocate_rva[ \t]*=[ \t]*([0-9]+)" "engine_allocate_rva" "${PROFILE_TEXT}" "${INPUT}")
    require_value(FREE_RVA "engine_free_rva[ \t]*=[ \t]*([0-9]+)" "engine_free_rva" "${PROFILE_TEXT}" "${INPUT}")
    require_value(OVERWRITE_SIZE "overwrite_size[ \t]*=[ \t]*([0-9]+)" "overwrite_size" "${PROFILE_TEXT}" "${INPUT}")
    require_value(SIGNATURE "signature[ \t]*=[ \t]*\"([0-9A-Fa-f ]+)\"" "signature" "${PROFILE_TEXT}" "${INPUT}")

    string(REGEX REPLACE " +" ";" SIGNATURE_BYTES "${SIGNATURE}")
    set(SIGNATURE_LIST "")
    set(SIGNATURE_SIZE 0)
    foreach(BYTE IN LISTS SIGNATURE_BYTES)
        if(NOT BYTE MATCHES "^[0-9A-Fa-f][0-9A-Fa-f]$")
            message(FATAL_ERROR "Invalid signature byte '${BYTE}' in ${INPUT}")
        endif()
        string(APPEND SIGNATURE_LIST "0x${BYTE}, ")
        math(EXPR SIGNATURE_SIZE "${SIGNATURE_SIZE} + 1")
    endforeach()
    if(SIGNATURE_SIZE LESS OVERWRITE_SIZE)
        message(FATAL_ERROR "Signature is shorter than overwrite_size in ${INPUT}")
    endif()

    string(APPEND PROFILE_DECLS
            "inline constexpr std::array<std::uint8_t, ${SIGNATURE_SIZE}> kGlobalInitSignature${PROFILE_INDEX}{${SIGNATURE_LIST}};\n")
    string(APPEND PROFILE_DECLS "inline constexpr EmbeddedBootstrapProfile kBootstrapProfile${PROFILE_INDEX}{\n")
    string(APPEND PROFILE_DECLS "    ${PE_TIMESTAMP}u, ${SIZE_OF_IMAGE}u, \"${BUILD}\",\n")
    string(APPEND PROFILE_DECLS
            "    ${WINDOW_RVA}u, ${REGISTRY_RVA}u, ${FROZEN_RVA}u, ${CLASS_COUNT_RVA}u, ${ALLOCATE_RVA}u, ${FREE_RVA}u,\n")
    string(APPEND PROFILE_DECLS
            "    ${OVERWRITE_SIZE}u, kGlobalInitSignature${PROFILE_INDEX}.data(), kGlobalInitSignature${PROFILE_INDEX}.size()};\n")
    list(APPEND PROFILE_NAMES "kBootstrapProfile${PROFILE_INDEX}")
    math(EXPR PROFILE_INDEX "${PROFILE_INDEX} + 1")
endforeach()

if(PROFILE_INDEX EQUAL 0)
    message(FATAL_ERROR "No bootstrap profiles were provided")
endif()

string(REPLACE ";" ", " PROFILE_NAME_LIST "${PROFILE_NAMES}")

get_filename_component(OUTPUT_DIR "${OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
file(WRITE "${OUTPUT}" "#pragma once\n\n")
file(APPEND "${OUTPUT}" "#include \"platform/windows/core/early_bootstrap.hpp\"\n\n")
file(APPEND "${OUTPUT}" "#include <array>\n#include <cstdint>\n\n")
file(APPEND "${OUTPUT}" "namespace rml::platform::windows::generated\n{\n")
file(APPEND "${OUTPUT}" "${PROFILE_DECLS}")
file(APPEND "${OUTPUT}" "inline constexpr std::array kBootstrapProfiles{${PROFILE_NAME_LIST}};\n")
file(APPEND "${OUTPUT}" "}\n")
